### ISSUE TITLE
Remove placeholder after a option has been selected

### ISSUE THREAD

**Issue by izzygld** [monterail/vue-multiselect#389]
Is there any 'Quick fix' to remove the ```:placeholder""``` after a option has been selected?

**Comment by shentao** [comment]
Fixed together with #379.

**Comment by yk1711** [comment]
Hi, the placeholder still shows when `:searchable="false"`. Is this expected for this mode or will get fixed ?

**Comment by arenddeboer** [comment]
I also see this behavior on version 2.0.2. The placeholder only goes away after I select a second item, but not on the first selected item. This is with :searchable="true"

**Comment by patricknavarro** [comment]
Has this been fixed? I'm still seeing it on 2.0.8.

**Comment by izzygld** [comment]
Sorry @patricknavarro don't think its fixed.
https://jsfiddle.net/shentao/jqofkzxc/

**Comment by philiplindberg** [comment]
Still seeing this in v2.1.0.

**Comment by vovasit91** [comment]
I'm using version for vue 1, and i done this with this css rule

.multiselect__tag~.multiselect__loading-transition~.multiselect__input{
        width: 1px;
        color: transparent;
    }
P.S. It can't be display:none because it loses focus event and closing starts working not correct.
Hope this helps somebody
